"""Generated digital-partition characterization report + freshness-pinned
generic envelope (issue #619). PDK-free; consumed by `sim/report/generate.py`.

The report is rendered from the machine-readable campaign file
`sim/digital-partition/runs/<record>/campaign.json` that the current
`records/LATEST` record names, so a number in the report cannot differ from the
number in the immutable evidence. With no record minted the report says so and
the `8.digital` signoff row stays uncited.

Freshness (`freshness_problems`): the campaign pins (a) a hash of the digital
PARTITION's netlist text (the `sar_sequencer` subcircuit plus the top-level
standard-cell glue instances extracted from `design/sar_adc_top.spice` -- an
analog-only edit to that file does not stale it), and (b) the routed DEF / GDS
hashes and composed placement origins the area was derived from. Any change to
those without a regenerated campaign is reported.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import digital_area
import digital_char as dc

DIGITAL_DIR = Path(__file__).resolve().parent
DOC_REL = "docs/characterization-report-digital.md"
ENVELOPE_REL = "signoff/evidence/digital-characterization.generic.json"


def partition_netlist_sha(top_netlist_text: str) -> str:
    dut = dc.extract_dut(top_netlist_text)
    body = "\n".join(dut["sequencer"] + dut["glue"]) + "\n"
    return "sha256:" + hashlib.sha256(body.encode()).hexdigest()


def latest_record(repo: Path) -> tuple[str, dict] | None:
    ptr = repo / "sim/digital-partition/records/LATEST"
    if not ptr.is_file():
        return None
    rid = ptr.read_text().strip().removesuffix(".md")
    camp = repo / "sim/digital-partition/runs" / rid / "campaign.json"
    if not camp.is_file():
        raise FileNotFoundError(f"records/LATEST names {rid} but {camp} is missing")
    return rid, json.loads(camp.read_text())


def freshness_problems(camp: dict, repo: Path) -> list[str]:
    problems: list[str] = []
    pinned = camp["pins"].get("digital partition netlist sha256")
    cur = partition_netlist_sha((repo / "design/sar_adc_top.spice").read_text())
    if pinned != cur:
        problems.append(
            f"digital partition netlist changed since the campaign ({pinned} -> {cur}); "
            "re-run sim/digital-partition/run_digital_partition.py --record")
    area = camp["summary"].get("area") or {}
    srcs = area.get("sources") or {}
    for macro, d in (("sar_sequencer", "layout/sar-sequencer"), ("top_glue", "layout/top-glue")):
        s = srcs.get(macro)
        if not s:
            problems.append(f"campaign has no area source for {macro}")
            continue
        rid = (repo / d / "reports" / "LATEST").read_text().strip()
        for kind, key in (("def", "def_sha256"), ("gds", "gds_sha256")):
            fname = s[kind].rsplit("/", 1)[1]
            cur_sha = digital_area.sha256_file(repo / d / "reports" / rid / fname)
            if cur_sha != s[key]:
                problems.append(f"{macro} routed {kind.upper()} changed since the campaign "
                                f"({s[key][:19]}... -> {cur_sha[:19]}...)")
    comp = srcs.get("composition") or {}
    top_rid = (repo / "layout/sar-adc-top/reports/LATEST").read_text().strip()
    creq = repo / "layout/sar-adc-top/reports" / top_rid / "compose.request.json"
    origins = json.loads(creq.read_text())["placement"]["origins_um"]
    for macro in ("sar_sequencer", "top_glue"):
        want = (comp.get("origins_um") or {}).get(macro)
        got = origins.get(macro)
        if want != got:
            problems.append(f"composed placement of {macro} changed since the campaign ({want} -> {got})")
    return problems


def _f(v) -> str:
    return "n/a" if v is None else f"{v:.2f}"


def render(repo: Path) -> str:
    L: list[str] = []
    a = L.append
    a("# sky130-sar-adc — Digital Partition Characterization")
    a("")
    a("Generated by `sim/report/generate.py` from the immutable digital-partition campaign "
      "(`sim/digital-partition/`). **Do not hand-edit.** Regenerate with `python3 "
      "sim/report/generate.py --write`; `--check` (wired into `npm run check:report`) fails if this "
      "file drifted, the cited record was superseded, or the partition netlist / routed layout "
      "changed without a regenerated campaign.")
    a("")
    a("This document backs T1 item 8's *digital* requirement (Fmax, area and power across the "
      "corner set). It characterizes the **digital partition only**: the walking-one ring "
      "sequencer / 10-bit register plus the top-level standard-cell glue named in "
      "`signoff/block-manifest.json`. **A digital clock-frequency bracket is not the ADC's "
      "conversion capability or sample rate**, which also depend on the sampling front end, the "
      "CDAC settling and the comparator decision time and remain governed by the analog report "
      "(`docs/characterization-report.md`) and the still-DRAFT sample-rate row.")
    a("")
    got = latest_record(repo)
    if got is None:
        a("## Status: no digital characterization record minted")
        a("")
        a("No `sim/digital-partition/records/LATEST` exists. The digital partition's Fmax, power "
          "and area across the corner set are **unmeasured**; the manifest's `8.digital` row is "
          "uncited and renders unmet/no_evidence.")
        a("")
        return "\n".join(L)
    rid, camp = got
    s = camp["summary"]
    a(f"Evidence: [`sim/digital-partition/records/{rid}.md`](../sim/digital-partition/records/{rid}.md) "
      f"(raw reports and decks under `sim/digital-partition/corners/{rid}/`, machine-readable "
      f"results in `sim/digital-partition/runs/{rid}/campaign.json`).")
    a("")
    meets = s["checklist"]["meets"]
    a(f"**Item-8 digital checklist (corner coverage, Fmax bracket or declared lower bound, power, "
      f"area, negative control): {'MET' if meets else 'NOT MET'}.**")
    if not meets:
        for r in s["checklist"]["reasons"]:
            a(f"- unmet: {r}")
    a("")
    a("## Frequency bracket (functional limit of the digital partition)")
    a("")
    a(f"Search grid {dc.F_BASE_MHZ:g} MHz x 2^(i/{dc.STEPS_PER_OCTAVE}) (adjacent points "
      f"{dc.tolerance_pct():.2f} % apart = the declared tolerance), ceiling "
      f"{dc.freq_mhz(dc.CEILING_INDEX):g} MHz. A censored row is a **lower bound**, not an Fmax.")
    a("")
    a("| Corner | State | Highest passing (MHz) | Next failing (MHz) | Non-monotone |")
    a("|---|---|---:|---:|---|")
    for cid, r in s["results"].items():
        a(f"| `{cid}` | {r['state']} | {_f(r['f_pass_mhz'])} | {_f(r['f_fail_mhz'])} | "
          f"{'YES' if r['non_monotone'] else 'no'} |")
    a("")
    nc = s["negative_control"]
    a(f"Negative control ({nc['f_mhz']:g} MHz, far too fast): "
      f"{'graded FAIL at every corner, as required' if nc['ok'] else 'NOT failing everywhere -- the checker is not trusted'}.")
    a("")
    a("## Power and energy at the provisional 12 MHz operating point")
    a("")
    a("| Corner | Functional | P_active (uW) | P_idle/reset (uW) | E/conversion (pJ) |")
    a("|---|---|---:|---:|---:|")
    for cid, p in s["power"].items():
        pa = "invalid" if p["p_active_w"] is None else f"{p['p_active_w'] * 1e6:.3f}"
        pr = "invalid" if p["p_reset_w"] is None else f"{p['p_reset_w'] * 1e6:.3f}"
        en = "invalid" if p["energy_per_conversion_j"] is None else f"{p['energy_per_conversion_j'] * 1e12:.3f}"
        fo = {True: "yes", False: "NO", None: "unknown"}[p["functional_at_op"]]
        a(f"| `{cid}` | {fo} | {pa} | {pr} | {en} |")
    a("")
    a("Digital rail `VPWR` (positive) against `VGND`; declared interface loads and a deterministic "
      "four-conversion COMP_OUT pattern; input-driver energy is outside the boundary. Full "
      "statement of loads, windows and switching pattern is in the record.")
    a("")
    ar = s.get("area")
    a("## Area (routed artifacts; geometry, not corner-dependent)")
    a("")
    if ar:
        a(f"- Composed footprint (bounding box of the two placed macros): {ar['composed_footprint_um2']:.1f} um^2")
        a(f"- Macro area (sum of the two DEF die areas; macros proven disjoint): {ar['macro_area_um2']:.1f} um^2")
        if "placed_cell_area_um2" in ar:
            a(f"- Placed-cell area (LEF footprints, incl. fill/tap): {ar['placed_cell_area_um2']:.1f} um^2; "
              f"logic cells only: {ar['logic_cell_area_um2']:.1f} um^2")
    else:
        a("- not derived")
    a("")
    a("## Declared limitations")
    a("")
    a("- Schematic-level transistor SPICE; no extracted parasitics, no routing RC. Not extracted "
      "timing and not static timing analysis; full-block post-layout verification remains separate.")
    a("- Loads and COMP_OUT arrival are experiment assumptions, not ratified spec values; the "
      "12 MHz point is the provisional DR-006-derived planning figure and the sample-rate target "
      "remains DRAFT.")
    a("- Pass means every sampled check held 0.9 T after each launching edge for every one of the four conversions.")
    a("")
    a("## Pins")
    a("")
    for k, v in camp["pins"].items():
        a(f"- {k}: `{v}`")
    a("")
    return "\n".join(L)


def build_envelope(repo: Path, doc_sha256: str) -> dict:
    """The generic evidence envelope for `8.digital`. Refuses (ValueError)
    unless the latest campaign meets the checklist, so a citation can never be
    minted for an unmet artifact."""
    got = latest_record(repo)
    if got is None:
        raise ValueError("no digital characterization record")
    rid, camp = got
    if not camp["summary"]["checklist"]["meets"]:
        raise ValueError("campaign does not meet the item-8 digital checklist: "
                         + "; ".join(camp["summary"]["checklist"]["reasons"]))
    return {
        "_comment": [
            "Generic evidence envelope (`\"kind\": \"generic\"`) wrapping",
            f"{DOC_REL} so `klt signoff --manifest` can grade the DIGITAL half of T1 item 8.",
            "GENERATED by `python3 sim/report/generate.py --write-envelope`; never hand-edited.",
            "",
            f"It asserts exactly that the campaign recorded in sim/digital-partition/records/{rid}.md",
            "covers all nine ratified corners with a frequency bracket (or declared lower bound), rail",
            "power / energy per conversion and routed area, with a too-fast-clock negative control that",
            "fails everywhere. It does NOT assert any spec row is met, and a digital clock bracket is",
            "not the ADC's sample rate. Schematic-level only; no extracted timing.",
            "",
            "FRESHNESS. provenance.input.content_hash is the sha256 of `source`; signoff/",
            "check_evidence_hashes.py re-hashes it on every push, and sim/report/generate.py --check",
            "rejects a digital-partition netlist or routed-layout change that lacks a regenerated",
            "campaign (the document embeds those pins).",
        ],
        "schema_version": 1,
        "kind": "generic",
        "status": "pass",
        "summary": ("Digital partition characterization: frequency bracket, rail power and energy "
                    "per conversion at nine ratified corners, routed area; generated by "
                    "sim/report/generate.py from the immutable campaign record."),
        "source": DOC_REL,
        "provenance": {"input": {"content_hash": doc_sha256}},
    }
