#!/usr/bin/env python3
"""Standalone runner for sim/cdac-array-transfer/ -- the CDAC array's DAC
transfer characteristic (code-vs-output linearity), issue #53.

WHY THIS IS ITS OWN SCRIPT, NOT sim/run_corners.py. The generic harness
(sim/harness/testbench.py's build_netlist()) unconditionally emits
`.control op ... .endc` -- a bare DC operating point. That is correct for
every existing sim/*/testbench/tb.json experiment (harness-corner-smoke,
mc-smoke) because none of them depends on the *history* of a floating
node. This experiment's DUT is a purely-capacitive, top-plate-sampling
network: at true DC, an ideal capacitor is an open circuit, so `.op` alone
would report whatever an arbitrary leak-resistor network implies -- NOT
the charge-redistribution result the CDAC array actually produces. The
physically-meaningful "DAC output for code C" requires a *transient*: pin
the top plate to Vcm while the bottom plates sit at a known baseline
(reset), then let the bottom plates step to their code-determined rails
and read the top plate after it settles (see the testbench fragment's own
header for the full derivation). Reusing sim/harness/pdk.py,
sim/harness/toolchain.py, sim/harness/measure.py and
sim/harness/evidence.py (unmodified) keeps this consistent with the rest
of the harness everywhere that isn't analysis-type-specific.

Usage:
    python3 sim/cdac-array-transfer/run_transfer.py --record
    python3 sim/cdac-array-transfer/run_transfer.py --check-env
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

SIM_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = SIM_DIR.parent
sys.path.insert(0, str(SIM_DIR))

from harness import corners as corners_mod  # noqa: E402
from harness import evidence, measure, pdk, toolchain  # noqa: E402

EXPERIMENT_DIR = Path(__file__).resolve().parent
FRAGMENT = EXPERIMENT_DIR / "testbench" / "tb_cdac_array_transfer.spice"

# Representative 9-bit sub-array codes (0..511) this experiment measures --
# see the fragment's own header for why these five (endpoints, quartiles,
# and the sub-array's own MSB carry at 256).
CODES = [0, 128, 256, 384, 511]

NOMINAL_SUPPLY_V = 1.8  # = V_DD, per DR-003 Item 1's recommendation
# (spec/decision-records/DR-003-numeric-spec-derivation.md), provisional
# pending #27 -- NOT a ratified spec value; used here only as the
# harness's own nominal test-supply convention (same role
# nominal_supply_v plays in every tb.json manifest).
SUPPLY_TOLERANCE = 0.10
TEMPS_C = [-40, 27, 125]
PROCESS_CORNERS = ["tt", "ss", "ff", "sf", "fs"]
SETTLE_T = "500n"
TRAN_STEP = "0.5n"


def ideal_vdiff(code: int, vdd_val: float) -> float:
    """Charge-conservation-derived ideal differential output for `code`
    (VREFN=0, Vcm=vdd_val/2, C_total=512 unit caps/side per DR-003 Item 3)
    -- see the fragment header for the derivation."""
    return vdd_val * (2 * code - 511) / 512


def build_netlist(info: pdk.PdkInfo, process_corner: str, temp_c: float, supply_v: float) -> str:
    lines: list[str] = []
    a = lines.append
    a("* cdac-array-transfer -- generated by sim/cdac-array-transfer/run_transfer.py (issue #53)")
    a(f"* corner={process_corner} temp={temp_c}C supply={supply_v}V")
    a(f".lib {info.ngspice_lib} {process_corner}")
    a(f".temp {temp_c}")
    a(f".param vdd_val = {supply_v}")
    a("")
    a(FRAGMENT.read_text())
    a("")
    a(".control")
    a(f"tran {TRAN_STEP} {SETTLE_T}")
    for code in CODES:
        a(f"meas tran vtop_p_{code} find v(top_{code}p) at={SETTLE_T}")
        a(f"meas tran vtop_n_{code} find v(top_{code}n) at={SETTLE_T}")
    a(".endc")
    a(".end")
    return "\n".join(lines) + "\n"


def measure_names() -> list[str]:
    names = []
    for code in CODES:
        names.append(f"vtop_p_{code}")
        names.append(f"vtop_n_{code}")
    return names


def run(process_corners=None, temps_c=None, quiet: bool = False):
    info = pdk.resolve()
    if not info.found:
        raise RuntimeError(f"PDK not resolvable: {info.error}")

    process_corners = process_corners or PROCESS_CORNERS
    temps_c = temps_c or TEMPS_C
    supply_points = corners_mod.supply_points(NOMINAL_SUPPLY_V, SUPPLY_TOLERANCE)

    baseline_process = "tt" if "tt" in process_corners else process_corners[0]
    baseline_temp = 27 if 27 in temps_c else temps_c[0]
    baseline_supply = NOMINAL_SUPPLY_V

    # See harness.corners.oat_grid()'s docstring for why this is a
    # one-at-a-time (OAT / "star") grid rather than a full factorial
    # |process|x|temp|x|supply| grid.
    grid = corners_mod.oat_grid(
        baseline_process,
        baseline_temp,
        baseline_supply,
        process_corners,
        temps_c,
        supply_points,
    )

    record_id = evidence.new_record_id()
    corners_out_dir = EXPERIMENT_DIR / "corners" / record_id

    names = measure_names()
    points = []
    import tempfile

    with tempfile.TemporaryDirectory(prefix="sim-cdac-transfer-") as scratch:
        scratch_dir = Path(scratch)
        for process_corner, temp_c, supply_v in grid:
            cid = corners_mod.corner_id(process_corner, temp_c, supply_v)
            netlist = build_netlist(info, process_corner, temp_c, supply_v)
            log_text = toolchain.run_ngspice(netlist, scratch_dir, cid)
            parsed = measure.parse(log_text, names)
            missing = measure.missing(parsed, names)
            per_code = {}
            for code in CODES:
                vp = parsed.get(f"vtop_p_{code}")
                vn = parsed.get(f"vtop_n_{code}")
                vdiff = (vp - vn) if (vp is not None and vn is not None) else None
                ideal = ideal_vdiff(code, supply_v)
                err_mv = (vdiff - ideal) * 1000.0 if vdiff is not None else None
                step_mv = 2 * supply_v / 512 * 1000.0
                err_pct_step = (err_mv / step_mv * 100.0) if err_mv is not None else None
                per_code[code] = dict(
                    vtop_p=vp, vtop_n=vn, vdiff=vdiff, ideal=ideal,
                    err_mv=err_mv, err_pct_step=err_pct_step,
                )
            points.append(dict(
                process_corner=process_corner, temp_c=temp_c, supply_v=supply_v,
                corner_id=cid, per_code=per_code, missing=missing, log_text=log_text,
            ))
            if not quiet:
                summary = ", ".join(
                    f"{c}:{per_code[c]['err_mv']:.3f}mV" if per_code[c]['err_mv'] is not None else f"{c}:MISSING"
                    for c in CODES
                )
                print(f"  {cid}: err(actual-ideal) {summary}")

    return record_id, corners_out_dir, points, info


def write_evidence(record_id, corners_out_dir, points, info, note: str = "", supersedes: str = ""):
    corners_out_dir.mkdir(parents=True, exist_ok=True)
    for p in points:
        (corners_out_dir / f"{p['corner_id']}.log").write_text(p["log_text"])

    record_path = evidence.write_netlist_snapshot(EXPERIMENT_DIR, record_id, FRAGMENT)
    netlist_sha = evidence.sha256_file(FRAGMENT)

    baseline = next(p for p in points if p["process_corner"] == "tt" and p["temp_c"] == 27
                     and abs(p["supply_v"] - NOMINAL_SUPPLY_V) < 1e-9)
    max_err_mv = max(
        abs(p["per_code"][c]["err_mv"])
        for p in points for c in CODES
        if p["per_code"][c]["err_mv"] is not None
    )
    max_err_pct_step = max(
        abs(p["per_code"][c]["err_pct_step"])
        for p in points for c in CODES
        if p["per_code"][c]["err_pct_step"] is not None
    )
    any_missing = any(p["missing"] for p in points)
    overall_ok = not any_missing

    lines: list[str] = []
    a = lines.append
    a(f"# Record {record_id}")
    a("")
    a(f"- **Record ID**: {record_id}")
    a(
        "- **Claim**: None (ratified) -- functional/linearity spot-check of the "
        "CDAC array's own DAC transfer characteristic (design/cdac/cdac_array.sch), "
        "in isolation from the sampling front end, comparator, and SAR logic, per "
        "issue #53's acceptance criteria. Informs, but does not substantiate, "
        "spec/target-spec.md's DNL/INL row (pending #1/#27 ratification and the "
        "formal Monte-Carlo campaign, #29)."
    )
    a("- **Netlist provenance**: schematic (`sim/cdac-array-transfer/testbench/tb_cdac_array_transfer.spice`,"
      " hand-authored to match `design/cdac/cdac_array.sch`'s unit-cell pattern and sizing --"
      " see that file's own header for why it is not xschem-netlisted directly)")
    process_corners_run = sorted({p["process_corner"] for p in points})
    temps_run = sorted({p["temp_c"] for p in points})
    supplies_run = sorted({p["supply_v"] for p in points})
    a(
        f"- **Corner matrix run**: process={process_corners_run}, "
        f"temperature_c={temps_run}, supply_v={supplies_run} "
        f"({len(points)} points, one-at-a-time per sim/README.md)"
    )
    a(
        "- **Linearity methodology**: `reduced-code-set-major-carry` -- 5 of the "
        "9-bit sub-array's 512 codes (0, 128, 256, 384, 511: both endpoints, the "
        "quartiles, and 256 = the sub-array's own MSB/major-carry position). This "
        "is a coarse functional spot-check of the transfer function's linearity "
        "and monotonicity across the code range, NOT the formal statistical "
        "DNL/INL characterization (that needs the full code ramp or code-density "
        "method plus mismatch Monte Carlo -- future work, #29)."
    )
    if note:
        a(f"- **Note**: {note}")
    a(f"- **Overall**: {'PASS' if overall_ok else 'FAIL'} (no ngspice measurement failures;"
      f" max |error| = {max_err_mv:.4f} mV = {max_err_pct_step:.2f}% of one array code-step"
      f" [{2*NOMINAL_SUPPLY_V/512*1000:.4f} mV @ nominal] across all corners and codes run --"
      f" informational, no ratified pass/fail threshold exists yet, per CLAUDE.md)")
    a("")
    a("## Per-corner, per-code results (actual vs. ideal charge-redistribution value)")
    a("")
    a("| corner-id | code | vtop_p (V) | vtop_n (V) | vdiff (V) | ideal vdiff (V) | error (mV) | error (% of code-step) |")
    a("|---|---|---|---|---|---|---|---|")
    for p in points:
        for c in CODES:
            d = p["per_code"][c]
            if d["vdiff"] is None:
                a(f"| `{p['corner_id']}` | {c} | MISSING | MISSING | - | - | - | - |")
                continue
            a(
                f"| `{p['corner_id']}` | {c} | {d['vtop_p']:.6g} | {d['vtop_n']:.6g} | "
                f"{d['vdiff']:.6g} | {d['ideal']:.6g} | {d['err_mv']:.4f} | {d['err_pct_step']:.3f} |"
            )
    a("")
    a("## Monotonicity check (baseline corner, tt/27C/1.8V)")
    a("")
    bvals = [(c, baseline["per_code"][c]["vdiff"]) for c in CODES]
    monotonic = all(bvals[i][1] < bvals[i + 1][1] for i in range(len(bvals) - 1))
    a(f"- code order {[c for c, _ in bvals]} -> vdiff {[round(v, 6) for _, v in bvals]}")
    a(f"- strictly increasing (monotonic): {'YES' if monotonic else 'NO'}")
    a("")
    lines.extend(evidence.environment_block(
        pdk_line=f"{info.variant} @ {pdk.resolved_commit(info)}",
        ngspice_line=toolchain._ngspice_version() or "unknown",
        netlist_sha256=netlist_sha,
    ))
    a("")
    lines.extend(evidence.footer_lines("sim/cdac-array-transfer/run_transfer.py", supersedes))

    record_path.write_text("\n".join(lines))
    return record_path, overall_ok


def main():
    ap = argparse.ArgumentParser(description="CDAC array DAC transfer-characteristic runner")
    ap.add_argument("--check-env", action="store_true")
    ap.add_argument("--record", action="store_true")
    ap.add_argument("--supersedes", default="")
    ap.add_argument("--note", default="")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    if args.check_env:
        info = pdk.resolve()
        print(f"PDK: found={info.found} variant={info.variant} error={info.error!r}")
        return 0 if info.found else 3

    info = pdk.resolve()
    if not info.found:
        print(f"SKIP: PDK not found ({info.error})")
        return 3

    record_id, corners_out_dir, points, info = run(quiet=args.quiet)
    if args.record:
        record_path, ok = write_evidence(
            record_id, corners_out_dir, points, info, note=args.note, supersedes=args.supersedes
        )
        print(f"wrote {record_path}")
        print("PASS" if ok else "FAIL")
        return 0 if ok else 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
