"""Monte Carlo runner: drives ngspice at a fixed PVT corner, varying only
ngspice's `rndseed` across N draws, and reports a distribution (mean,
stdev, min, max) for each measured quantity plus an explicit negative
control.

A data converter's statistical evidence rows (ENOB, INL/DNL, offset -- see
CLAUDE.md "Verification is the product" and spec/target-spec.md "What T1
will require of this block") are Monte Carlo distributions, not single
points, and every one needs: a recorded seed, a sample count, and a
negative control that proves the pipeline can tell "real statistical
variation" apart from "the harness always reports some nonzero spread".

This module supplies the *mechanism* against a harness-proof circuit (see
sim/mc-smoke/), not ENOB/INL/DNL/offset from a real ADC -- there is no ADC
schematic yet (see sim/README.md "Harness self-test experiments"). A future
ADC testbench manifest reuses this exact module.

sky130's per-instance local-mismatch switch (MC_MM_SWITCH=1, entered via
the '<corner>_mm' .lib sections -- see sim/pdk.json's notes) is what
actually randomizes anything: at a plain (non-'_mm') corner, AGAUSS() terms
inside the device subcircuits are disabled, so `rndseed` has NO effect on
the measured value -- this is the negative control's mechanism, verified
empirically (see sim/mc-smoke/records/), not assumed.
"""

from __future__ import annotations

import shutil
import statistics
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from . import evidence, measure, pdk, testbench

SIM_DIR = Path(__file__).resolve().parent.parent


@dataclass
class Draw:
    seed: int
    measures: dict[str, float]
    log_text: str


@dataclass
class Distribution:
    name: str
    values: list[float]

    @property
    def n(self) -> int:
        return len(self.values)

    @property
    def mean(self) -> float:
        return statistics.fmean(self.values) if self.values else float("nan")

    @property
    def stdev(self) -> float:
        return statistics.pstdev(self.values) if len(self.values) > 1 else 0.0

    @property
    def minimum(self) -> float:
        return min(self.values) if self.values else float("nan")

    @property
    def maximum(self) -> float:
        return max(self.values) if self.values else float("nan")


@dataclass
class McResult:
    manifest: testbench.Manifest
    process_corner: str
    mismatch_corner: str
    temp_c: float
    supply_v: float
    seed: int
    n: int
    draws: list[Draw]
    negative_control_draws: list[Draw]
    record_id: str
    netlist_sha256: str


def _run_ngspice(netlist_text: str, scratch_dir: Path, log_name: str) -> str:
    scratch_dir.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(SIM_DIR / "spiceinit", scratch_dir / ".spiceinit")
    netlist_path = scratch_dir / f"{log_name}.spice"
    netlist_path.write_text(netlist_text)
    proc = subprocess.run(
        ["ngspice", "-b", str(netlist_path)],
        cwd=scratch_dir,
        capture_output=True,
        text=True,
        timeout=120,
    )
    return proc.stdout + proc.stderr


def _build_mc_netlist(
    manifest: testbench.Manifest,
    pdk_info: pdk.PdkInfo,
    lib_corner: str,
    temp_c: float,
    supply_v: float,
    seed: int,
) -> str:
    lines: list[str] = []
    a = lines.append
    a(f"* {manifest.name} -- Monte Carlo draw, generated by sim/harness (issue #2)")
    a(f"* corner={lib_corner} temp={temp_c}C supply={supply_v}V seed={seed}")
    a(f".lib {pdk_info.ngspice_lib} {lib_corner}")
    a(f".temp {temp_c}")
    a(f".param vdd_val = {supply_v}")
    a(f".option rndseed={seed}")
    a("")
    a(manifest.netlist_fragment.read_text())
    a("")
    a(".control")
    a("op")
    for name, expr in manifest.measure.items():
        a(f"let {name} = {expr}")
        a(f"print {name}")
    a(".endc")
    a(".end")
    return "\n".join(lines) + "\n"


def run(
    manifest: testbench.Manifest,
    process_corner: str,
    temp_c: float,
    supply_v: float,
    seed: int,
    n: int,
    quiet: bool = False,
) -> McResult:
    """Draw n samples at <process_corner>_mm (mismatch enabled), plus n
    samples at the plain process_corner (mismatch DISABLED) as the
    deterministic negative control -- the same seed sequence is reused for
    both, so a harness bug that ignores rndseed shows up as the "real"
    draws collapsing to a point too, not just the control looking wrong.
    """
    info = pdk.resolve()
    if not info.found:
        raise RuntimeError(f"PDK not resolvable: {info.error}")

    from . import corners as corners_mod

    mismatch_corner = corners_mod.mismatch_corner_for(process_corner)
    record_id = evidence.new_record_id()
    netlist_sha = evidence.sha256_file(manifest.netlist_fragment)

    draws: list[Draw] = []
    negative_control_draws: list[Draw] = []

    with tempfile.TemporaryDirectory(prefix="sim-harness-mc-") as scratch:
        scratch_dir = Path(scratch)
        for i in range(n):
            this_seed = seed + i
            netlist = _build_mc_netlist(manifest, info, mismatch_corner, temp_c, supply_v, this_seed)
            log_text = _run_ngspice(netlist, scratch_dir, f"draw_{i}")
            parsed = measure.parse(log_text, list(manifest.measure.keys()))
            draws.append(Draw(seed=this_seed, measures=parsed, log_text=log_text))
            if not quiet:
                print(f"  draw {i} (seed={this_seed}, {mismatch_corner}): {parsed}")

        for i in range(n):
            this_seed = seed + i
            netlist = _build_mc_netlist(manifest, info, process_corner, temp_c, supply_v, this_seed)
            log_text = _run_ngspice(netlist, scratch_dir, f"neg_{i}")
            parsed = measure.parse(log_text, list(manifest.measure.keys()))
            negative_control_draws.append(Draw(seed=this_seed, measures=parsed, log_text=log_text))
            if not quiet:
                print(f"  negative-control {i} (seed={this_seed}, {process_corner}): {parsed}")

    return McResult(
        manifest=manifest,
        process_corner=process_corner,
        mismatch_corner=mismatch_corner,
        temp_c=temp_c,
        supply_v=supply_v,
        seed=seed,
        n=n,
        draws=draws,
        negative_control_draws=negative_control_draws,
        record_id=record_id,
        netlist_sha256=netlist_sha,
    )


def distributions(draws: list[Draw], names: list[str]) -> dict[str, Distribution]:
    out = {}
    for name in names:
        values = [d.measures[name] for d in draws if name in d.measures]
        out[name] = Distribution(name=name, values=values)
    return out


def negative_control_ok(result: McResult, names: list[str]) -> tuple[bool, list[str]]:
    """The negative control passes iff every measurement is EXACTLY
    reproducible across draws when mismatch is disabled (stdev == 0) --
    proving the harness distinguishes "mismatch active" from "mismatch
    off" rather than always reporting some canned spread. A nonzero
    negative-control stdev means either mismatch leaked into the disabled
    corner, or the measurement itself is corner/seed-sensitive for a
    reason unrelated to device mismatch -- either way, the "real" draws'
    spread cannot be trusted until this is fixed.
    """
    dists = distributions(result.negative_control_draws, names)
    failures = []
    for name, dist in dists.items():
        if dist.n == 0:
            failures.append(f"{name}: no negative-control samples parsed")
        elif dist.stdev != 0.0:
            failures.append(
                f"{name}: negative control stdev={dist.stdev:.6g} != 0 "
                f"(values={dist.values})"
            )
    return (not failures, failures)


def write_evidence(result: McResult, note: str = "", supersedes: str = "") -> Path:
    manifest = result.manifest
    experiment_dir = manifest.experiment_dir
    names = list(manifest.measure.keys())

    draws_dir = experiment_dir / "mc-draws" / result.record_id
    draws_dir.mkdir(parents=True, exist_ok=True)
    for i, d in enumerate(result.draws):
        (draws_dir / f"draw_{i}_seed{d.seed}.log").write_text(d.log_text)
    for i, d in enumerate(result.negative_control_draws):
        (draws_dir / f"negctrl_{i}_seed{d.seed}.log").write_text(d.log_text)

    snapshots_dir = experiment_dir / "netlist-snapshots"
    snapshots_dir.mkdir(parents=True, exist_ok=True)
    (snapshots_dir / f"{result.record_id}.spice").write_text(
        manifest.netlist_fragment.read_text()
    )

    records_dir = experiment_dir / "records"
    records_dir.mkdir(parents=True, exist_ok=True)
    record_path = records_dir / f"{result.record_id}.md"

    dists = distributions(result.draws, names)
    ctrl_ok, ctrl_failures = negative_control_ok(result, names)

    info = pdk.resolve()

    lines: list[str] = []
    a = lines.append
    a(f"# Monte Carlo record {result.record_id}")
    a("")
    a(f"- **Record ID**: {result.record_id}")
    a(f"- **Claim**: {manifest.claim}")
    a(f"- **Netlist provenance**: schematic (`{manifest.netlist_fragment.relative_to(evidence.REPO_ROOT)}`)")
    a(
        f"- **Statistical convention**: mismatch corner `{result.mismatch_corner}`, "
        f"N={result.n}, seed={result.seed} (draws use seed, seed+1, ..., seed+N-1), "
        f"PVT point process={result.process_corner} temp={result.temp_c}C supply={result.supply_v}V"
    )
    a(
        f"- **Negative control**: N={result.n} draws at the plain "
        f"`{result.process_corner}` corner (mismatch DISABLED), same seed "
        f"sequence -- {'PASS (stdev == 0 on every measurement)' if ctrl_ok else 'FAIL: ' + '; '.join(ctrl_failures)}"
    )
    if note:
        a(f"- **Note**: {note}")
    overall_ok = ctrl_ok
    a(f"- **Overall**: {'PASS' if overall_ok else 'FAIL'}")
    a("")
    a("## Distributions (mismatch-enabled draws)")
    a("")
    a("| measurement | N | mean | stdev | min | max |")
    a("|---|---|---|---|---|---|")
    for name in names:
        d = dists[name]
        a(f"| `{name}` | {d.n} | {d.mean:.6g} | {d.stdev:.6g} | {d.minimum:.6g} | {d.maximum:.6g} |")
    a("")
    a("## Negative control (mismatch-disabled draws)")
    a("")
    ctrl_dists = distributions(result.negative_control_draws, names)
    a("| measurement | N | mean | stdev (must be 0) | min | max |")
    a("|---|---|---|---|---|---|")
    for name in names:
        d = ctrl_dists[name]
        a(f"| `{name}` | {d.n} | {d.mean:.6g} | {d.stdev:.6g} | {d.minimum:.6g} | {d.maximum:.6g} |")
    a("")
    lines.extend(evidence.environment_block(
        pdk_line=f"{info.variant} @ {pdk.resolved_commit(info)}",
        ngspice_line=_ngspice_version_str(),
        netlist_sha256=result.netlist_sha256,
        extra={"MC seed": str(result.seed), "MC N": str(result.n)},
    ))
    a("")
    a(f"- **Supersedes**: {supersedes or '(none)'}")
    a("")
    a(
        "Written by `sim/monte_carlo.py`. Append-only: never edit or delete "
        "this file -- a re-run or correction mints a new record-id and "
        "points back here via **Supersedes** (see `sim/README.md`)."
    )
    a("")

    record_path.write_text("\n".join(lines))
    return record_path


def _ngspice_version_str() -> str:
    from . import toolchain

    return toolchain._ngspice_version() or "unknown"
